version: '2'

services:
  web:
    image: coinflippers/slotmachine
    container_name: web
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slotmachine-test
    command: npm run test:integration

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
