version: '2'

services:
  web:
    image: coinflippers/slotmachine
    container_name: web
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slotmachine-test
    command: npm run test:integration

  mongo:
    image: mongo:3.4.10-jessie
    ports:
      - "27017:27017"
