version: 2
jobs:
  build-job:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.9.1
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys: 
            - slotmachine-npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - slotmachine-npm-deps-{{ .Branch }}-
            - slotmachine-npm-deps-
      - run:
          name: Install dependencies
          command: yarn
      - run: mkdir ~/test-results
      - run: 
          command: |
            npm test
            cp junit.xml ~/test-results/junit.xml
          when: always
      - save_cache:
          key: slotmachine-npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/node_modules"
      - run: docker build -t coinflippers/slotmachine .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push coinflippers/slotmachine
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  deploy-job:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    working_directory: ~/tmp
    steps:
      - run: ansible-playbook -i devops/inventory.yml devops/deploy.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master