version: 2
dependencies:
  pre:
    - pip install ansible
    - pip install --upgrade setuptools
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deployment:
    prod:
      branch: master
      commands:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push coinflippers/slotmachine
        - ansible-playbook -i devops/inventory.yml devops/deploy.yml