version: 2
dependencies:
  pre:
    - pip install ansible
    - pip install --upgrade setuptools
    
jobs:
  build-job:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.9.1
    steps:
      - setup_remote_docker
      - checkout
      - run: npm install
      - run: npm test
      - run: docker build -t coinflippers/slotmachine .

  deploy-job:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/tmp
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push coinflippers/slotmachine
      - run: ansible-playbook -i devops/inventory.yml devops/deploy.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master