version: 2
dependencies:
  pre:
    - pip install ansible
    - pip install --upgrade setuptools
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.9.1
    steps:
      - setup_remote_docker
      - checkout
      - run: npm install
      - run: npm test
      - run: docker build -t coinflippers/slotmachine .

  deployment:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/tmp
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push coinflippers/slotmachine
      - run: ansible-playbook -i devops/inventory.yml devops/deploy.yml