---
- name: Create working directory
  file:
    path: "{{ working_directory }}"
    state: directory

- name: Stop system nginx service
  service:
    name: nginx
    state: stopped
  ignore_errors: yes

- name: Copy nginx configuration
  copy:
    src: nginx.conf
    dest: "{{ working_directory }}/nginx.conf"

- name: Login to Docker Hub
  shell: docker login -u {{ DOCKER_USER }} -p {{ DOCKER_PASSWORD }}

- name: Pull Docker Hub image
  shell: docker pull {{ docker_image }}

- name: Copy docker-compose.staging.yml
  template:
    src: docker-compose.staging.yml.j2
    dest: "{{ working_directory }}/docker-compose.staging.yml"

- name: Start server containers
  shell: docker-compose -f docker-compose.staging.yml up -d
  args:
    chdir: "{{ working_directory }}"

- name: Remove dangling images
  shell: docker rmi $(docker images -qa -f "dangling=true")